<?php

use Illuminate\Database\Seeder;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      $paises = \Illuminate\Support\Facades\DB::connection('diariasProducao')->table('pais')
      ->where('flag_seq', true)
      ->orderBy('id_pais', 'ASC')
      ->get();

      $codigos = [
        'BRASIL' => 'BR',
        'AFEGANISTÃO' => 'AF',
        'ÁFRICA DO SUL' => 'ZA',
        'ALBÂNIA' => ' AL',
        'ALEMANHA' => 'DE',
        'ANDORRA' => 'AD',
        'ANGOLA' => 'AO',
        'ANTÍGUA E BARBUDA' => 'AG',
        'ARÁBIA SAUDITA' => 'SA',
        'ARGÉLIA' => 'DZ',
        'ARGENTINA' => 'AR',
        'ARMÊNIA' => 'AM',
        'AUSTRÁLIA' => 'AU',
        'ÁUSTRIA' => 'AT',
        'AZERBAIDJÃO' => '',
        'BAHAMAS' => 'BS',
        'BANGLADESH' => 'BD',
        'BARBADOS' => 'BB',
        'BAREINE' => 'BH',
        'BELARUS' => 'BY',
        'BÉLGICA' => 'BE',
        'BELIZE' => 'BZ',
        'BENIN' => 'BJ',
        'BOLIVIA' => 'BO',
        'BÓSNIA-HERZEGÓVINA' => 'BA',
        'BOTSUANA' => 'BW',
        'BRUNEI DARUSSALAM' => 'BN',
        'BULGÁRIA' => 'BG',
        'BURKINA-FASSO' => 'BF',
        'BURUNDI' => 'BI',
        'BUTÃO' => 'BT',
        'CABO VERDE' => 'CV',
        'CAMARÕES' => 'CM',
        'CAMBOJA' => 'KH',
        'CANADÁ' => 'CA',
        'CATAR' => 'QA',
        'CAZAQUISTÃO' => 'KZ',
        'CHADE' => 'TD',
        'CHILE' => 'CL',
        'CHINA' => 'CN',
        'CHIPRE' => 'CY',
        'CINGAPURA' => '',
        'COLÔMBIA' => 'CO',
        'COMORES' => 'KM',
        'CONGO' => 'CG',
        'CORÉIA DO SUL' => '',
        'COSTA DO MARFIM' => 'CI',
        'COSTA RICA' => 'CR',
        'CROÁCIA' => 'HR',
        'CUBA' => 'CU',
        'DINAMARCA' => 'DK',
        'DJIBUTI' => 'DJ',
        'DOMINICA' => 'DM',
        'EGITO' => 'EG',
        'EL SALVADOR' => 'SV',
        'EMIRADOS ÁRABES' => 'AE',
        'EQUADOR' => 'EC',
        'ERITRÉIA' => 'ER',
        'ESLOVÊNIA' => 'SI',
        'ESPANHA' => 'ES',
        'ESTADOS UNIDOS DA AMÉRICA' => 'US',
        'ESTÔNIA' => 'EE',
        'ETIÓPIA' => 'ET',
        'FIJI' => 'FJ',
        'FILIPINAS' => 'PH',
        'FINLÂNDIA' => 'FI',
        'FRANÇA' => 'FR',
        'GABÃO' => 'GA',
        'GÂMBIA' => 'GM',
        'GANA' => 'GH',
        'GEÓRGIA' => 'GE',
        'GRANADA' => 'GD',
        'GRÉCIA' => 'GR',
        'GUATEMALA' => 'GT',
        'GUIANA' => 'GF',
        'GUINÉ' => 'GN',
        'GUINÉ BISSAU' => 'GW',
        'GUINÉ-EQUATORIAL' => 'GQ',
        'HAITI' => 'HT',
        'HONDURAS' => 'HN',
        'HONG KONG' => 'HK',
        'HUNGRIA' => 'HU',
        'IÊMEN' => 'YE',
        'ILHAS MARSHALL' => 'MH',
        'ÍNDIA' => 'IN',
        'INDONÉSIA' => 'ID',
        'IRÃ' => 'IR',
        'IRAQUE' => 'IQ',
        'IRLANDA' => 'IE',
        'ISLÂNDIA' => 'IS',
        'ISRAEL' => 'IL',
        'ITÁLIA' => 'IT',
        'JAMAICA' => 'JM',
        'JAPÃO' => 'JP',
        'JORDÂNIA' => 'JO',
        'KIRIBATI' => 'KI',
        'KUAITE' => 'KW',
        'LAOS' => 'LA',
        'LESOTO' => 'LS',
        'LETÔNIA' => 'LV',
        'LÍBANO' => 'LB',
        'LIBÉRIA' => 'LR',
        'LÍBIA' => 'LY',
        'LIECHTENSTEIN' => 'LI',
        'LITUÂNIA' => 'LT',
        'LUXEMBURGO' => 'LU',
        'MACEDÔNIA' => 'MK',
        'MADAGASCAR' => 'MG',
        'MALÁSIA' => 'MY',
        'MALAUÍ' => 'MW',
        'MALDIVAS' => 'MV',
        'MALI' => 'ML',
        'MALTA' => 'MT',
        'MARROCOS' => 'MA',
        'MAURÍCIO' => 'MU',
        'MAURITÂNIA' => 'MR',
        'MÉXICO' => 'MX',
        'MICRONÉSIA' => 'FM',
        'MOÇAMBIQUE' => 'MZ',
        'MOLDÁVIA' => '',
        'MÔNACO' => 'MC',
        'MONGÓLIA' => 'MN',
        'MONTENEGRO' => '',
        'MYANMAR' => '',
        'NAMÍBIA' => 'NA',
        'NAURU' => 'NR',
        'NEPAL' => 'NP',
        'NICARÁGUA' => 'NI',
        'NÍGER' => 'NE',
        'NIGÉRIA' => 'NG',
        'NORUEGA' => 'NO',
        'NOVA ZELÂNDIA' => 'NZ',
        'OMÃ' => 'OM',
        'PAÍSES BAIXOS' => 'PB',
        'PALAU' => 'PW',
        'PANAMÁ' => 'PA',
        'PAPUA NOVA GUINÉ' => 'PG',
        'PAQUISTÃO' => 'PK',
        'PARAGUAI' => 'PY',
        'PERU' => 'PE',
        'POLÔNIA' => 'PL',
        'PORTUGAL' => 'PT',
        'QUÊNIA' => 'KE',
        'REINO UNIDO' => 'GB',
        'REP. CENTRO AFRICANA' => 'CF',
        'REP. TOGOLESA' => '',
        'REPÚBLICA DEMOCRÁTICA DO CONGO' => '',
        'REPÚBLICA DOMINICANA' => 'DO',
        'REPÚBLICA ESLOVACA' => '',
        'REPÚBLICA POPULAR DA CORÉIA' => '',
        'REPÚBLICA QUIRGUIZ' => '',
        'REPÚBLICA TCHECA' => 'CZ',
        'ROMÊNIA' => 'RO',
        'RUANDA' => 'RW',
        'RÚSSIA' => '',
        'SALOMÃO' => 'SB',
        'SAMOA' => '',
        'SAN MARINO' => 'SM',
        'SANTA LÚCIA' => 'LC',
        'SÃO CRISTOVÃO E NÉVIS' => 'KN',
        'SÃO TOMÉ E PRÍNCIPE' => 'ST',
        'SÃO VICENTE E GRANADINAS' => 'VC',
        'SEICHELES' => '',
        'SENEGAL' => 'SN',
        'SERRA LEOA' => 'SL',
        'SÉRVIA' => '',
        'SIRIA' => 'SY',
        'SOMÁLIA' => 'SO',
        'SRI LANKA' => 'LK',
        'SUAZILÂNDIA' => 'SZ',
        'SUDÃO' => 'SD',
        'SUÉCIA' => 'SE',
        'SUÍÇA' => 'CH',
        'SURINAME' => 'SR',
        'TADJIQUISTÃO' => '',
        'TAILÂNDIA' => 'TH',
        'TAIWAN' => 'TW',
        'TANZÂNIA' => 'TZ',
        'TIMOR LESTE' => 'TL',
        'TONGA' => 'TO',
        'TRINIDAD E TOBAGO' => 'TT',
        'TUNÍSIA' => 'TN',
        'TURCOMENISTÃO' => 'TM',
        'TURQUIA' => 'TR',
        'TUVALU' => 'TV',
        'UCRÂNIA' => 'UA',
        'UGANDA' => 'UG',
        'URUGUAI' => 'UY',
        'UZBEQUISTÃO' => 'UZ',
        'VANUATU' => 'VU',
        'VENEZUELA' => 'VE',
        'VIETNÃ' => 'VN',
        'ZÂMBIA' => 'ZM',
        'ZIMBÁBUE' => 'ZW'
      ];
      
      foreach ($paises as $pais) {

        $nomePais = ucfirst(strtolower($pais->nome_pais));
        $paisExiste = \Diarias\Pais\Models\PaisModel::where('pais_nome', '=', $nomePais)->first();

        if ($paisExiste)
        {
            continue;
        }

        $novoPais = new \Diarias\Pais\Models\PaisModel();

        $novoPais->pais_nome = $nomePais;
        $novoPais->pais_codigo = $codigos[$pais->nome_pais];
        $novoPais->created_by = 1;

        $novoPais->save();
    }
      
    }
}
