###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    postgres:
      image: postgres:11.1-alpine
      container_name: api-diarias-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=diarias_root
        - POSTGRES_PASSWORD=diarias_pw
        - POSTGRES_DB=diarias_db
      ports:
        - "8004:5432"

    webserver:
      image: nginx:alpine
      container_name: api-diarias-webserver
      working_dir: /application
      volumes:
          - ./api/:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8005:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: api-diarias-php-fpm
      working_dir: /application
      volumes:
        - ./api/:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

